const standardsTrust = {
  sourceChecked: "2026-07-13",
  parseStatus: "Synthetic fixture — not parser output",
  rightsTier: "A — approved standards seed",
  rightsScopes: ["metadata", "rendered text", "API output"],
  dataRelease: "phase0-synthetic-1"
};

export const records = [
  {
    ...standardsTrust,
    module: "IF-MIB",
    symbol: "ifOperStatus",
    oid: "1.3.6.1.2.1.2.2.1.8",
    kind: "column",
    access: "read-only",
    syntax: "INTEGER { up(1), down(2), testing(3), unknown(4), dormant(5), notPresent(6), lowerLayerDown(7) }",
    revision: "2000-06-14",
    source: "IETF RFC 2863",
    sourceUrl: "https://www.rfc-editor.org/rfc/rfc2863.html",
    parent: "ifEntry",
    table: "ifTable",
    index: "ifIndex",
    related: ["linkDown", "linkUp", "ifAdminStatus"],
    intent: ["interface status", "port state", "link state"],
    description: "Current operational state of an interface.",
    enumValues: ["up(1)", "down(2)", "testing(3)", "unknown(4)", "dormant(5)", "notPresent(6)", "lowerLayerDown(7)"],
    command: "snmpget -v2c -c <community> <host> 1.3.6.1.2.1.2.2.1.8.<ifIndex>"
  },
  {
    ...standardsTrust,
    module: "IF-MIB",
    symbol: "ifDescr",
    oid: "1.3.6.1.2.1.2.2.1.2",
    kind: "column",
    access: "read-only",
    syntax: "DisplayString (SIZE (0..255))",
    revision: "2000-06-14",
    source: "IETF RFC 2863",
    sourceUrl: "https://www.rfc-editor.org/rfc/rfc2863.html",
    parent: "ifEntry",
    table: "ifTable",
    index: "ifIndex",
    related: ["ifName", "ifAlias", "ifOperStatus"],
    intent: ["interface description", "port description", "interface name"],
    description: "Human-readable information about an interface.",
    enumValues: [],
    command: "snmpwalk -v2c -c <community> <host> 1.3.6.1.2.1.2.2.1.2"
  },
  {
    ...standardsTrust,
    module: "IF-MIB",
    symbol: "ifName",
    oid: "1.3.6.1.2.1.31.1.1.1.1",
    kind: "column",
    access: "read-only",
    syntax: "DisplayString",
    revision: "2000-06-14",
    source: "IETF RFC 2863",
    sourceUrl: "https://www.rfc-editor.org/rfc/rfc2863.html",
    parent: "ifXEntry",
    table: "ifXTable",
    index: "ifIndex",
    related: ["ifDescr", "ifAlias", "ifOperStatus"],
    intent: ["interface name", "port name"],
    description: "Textual name of an interface assigned by the local device.",
    enumValues: [],
    command: "snmpwalk -v2c -c <community> <host> 1.3.6.1.2.1.31.1.1.1.1"
  },
  {
    ...standardsTrust,
    module: "SNMPv2-MIB",
    symbol: "sysUpTime",
    oid: "1.3.6.1.2.1.1.3",
    kind: "scalar",
    access: "read-only",
    syntax: "TimeTicks",
    revision: "2002-10-16",
    source: "IETF RFC 3418",
    sourceUrl: "https://www.rfc-editor.org/rfc/rfc3418.html",
    parent: "system",
    table: null,
    index: ".0 instance",
    related: ["sysName", "sysDescr", "coldStart"],
    intent: ["uptime", "device uptime", "restart time"],
    description: "Time since the network management portion was last initialized.",
    enumValues: [],
    command: "snmpget -v2c -c <community> <host> 1.3.6.1.2.1.1.3.0"
  },
  {
    ...standardsTrust,
    module: "HOST-RESOURCES-MIB",
    symbol: "hrProcessorLoad",
    oid: "1.3.6.1.2.1.25.3.3.1.2",
    kind: "column",
    access: "read-only",
    syntax: "Integer32 (0..100)",
    revision: "2000-03-06",
    source: "IETF RFC 2790",
    sourceUrl: "https://www.rfc-editor.org/rfc/rfc2790.html",
    parent: "hrProcessorEntry",
    table: "hrProcessorTable",
    index: "hrDeviceIndex",
    related: ["hrDeviceDescr", "hrSystemUptime"],
    intent: ["processor load", "cpu usage", "cpu load"],
    description: "One-minute average percentage of processor busy time.",
    enumValues: [],
    command: "snmpwalk -v2c -c <community> <host> 1.3.6.1.2.1.25.3.3.1.2"
  },
  {
    ...standardsTrust,
    module: "IF-MIB",
    symbol: "linkDown",
    oid: "1.3.6.1.6.3.1.1.5.3",
    kind: "notification",
    access: "not-accessible",
    syntax: "NOTIFICATION-TYPE",
    revision: "2000-06-14",
    source: "IETF RFC 2863",
    sourceUrl: "https://www.rfc-editor.org/rfc/rfc2863.html",
    parent: "snmpTraps",
    table: null,
    index: null,
    related: ["ifIndex", "ifAdminStatus", "ifOperStatus"],
    intent: ["link down trap", "interface down notification"],
    description: "Signals that an interface entered the down state.",
    enumValues: [],
    command: "# Notification OID; inspect its varbind objects instead of polling this OID."
  }
];
