const standardsTrust = {
  sourceChecked: "2026-07-14",
  parseStatus: "mibvendor-authored synthetic fixture — not parser output",
  publicationStatus: "public-alpha-synthetic",
  rightsTier: "A — mibvendor-authored metadata and paraphrase",
  rightsScopes: ["metadata", "rendered text", "API output"],
  dataRelease: "rights-cleared-2026-07-14.1"
};

export const records = [
  {
    ...standardsTrust,
    module: "IF-MIB",
    symbol: "ifOperStatus",
    oid: "1.3.6.1.2.1.2.2.1.8",
    kind: "column",
    access: "read-only",
    status: "current",
    syntax: "INTEGER { up(1), down(2), testing(3), unknown(4), dormant(5), notPresent(6), lowerLayerDown(7) }",
    syntaxDetail: {
      base: "INTEGER",
      textualConvention: null,
      displayHint: null,
      units: null,
      constraints: [],
      enums: { "1": "up", "2": "down", "3": "testing", "4": "unknown", "5": "dormant", "6": "notPresent", "7": "lowerLayerDown" },
      bits: {}
    },
    revision: "2000-06-14",
    source: "IETF RFC 2863",
    sourceUrl: "https://www.rfc-editor.org/rfc/rfc2863.html",
    parent: "ifEntry",
    table: "ifTable",
    row: "ifEntry",
    index: "ifIndex",
    notificationObjects: [],
    related: ["linkDown", "linkUp", "ifAdminStatus"],
    intent: ["interface status", "port state", "link state"],
    description: "Current operational state of an interface.",
    enumValues: ["up(1)", "down(2)", "testing(3)", "unknown(4)", "dormant(5)", "notPresent(6)", "lowerLayerDown(7)"],
    command: "snmpget -v2c -c <community> <host> 1.3.6.1.2.1.2.2.1.8.<ifIndex>"
  },
  {
    ...standardsTrust,
    module: "IF-MIB",
    symbol: "ifDescr",
    oid: "1.3.6.1.2.1.2.2.1.2",
    kind: "column",
    access: "read-only",
    status: "current",
    syntax: "DisplayString (SIZE (0..255))",
    syntaxDetail: {
      base: "OCTET STRING",
      textualConvention: "DisplayString",
      displayHint: "255a",
      units: null,
      constraints: ["SIZE (0..255)"],
      enums: {},
      bits: {}
    },
    revision: "2000-06-14",
    source: "IETF RFC 2863",
    sourceUrl: "https://www.rfc-editor.org/rfc/rfc2863.html",
    parent: "ifEntry",
    table: "ifTable",
    row: "ifEntry",
    index: "ifIndex",
    notificationObjects: [],
    related: ["ifName", "ifAlias", "ifOperStatus"],
    intent: ["interface description", "port description", "interface name"],
    description: "Human-readable information about an interface.",
    enumValues: [],
    command: "snmpwalk -v2c -c <community> <host> 1.3.6.1.2.1.2.2.1.2"
  },
  {
    ...standardsTrust,
    module: "IF-MIB",
    symbol: "ifName",
    oid: "1.3.6.1.2.1.31.1.1.1.1",
    kind: "column",
    access: "read-only",
    status: "current",
    syntax: "DisplayString",
    syntaxDetail: {
      base: "OCTET STRING",
      textualConvention: "DisplayString",
      displayHint: "255a",
      units: null,
      constraints: [],
      enums: {},
      bits: {}
    },
    revision: "2000-06-14",
    source: "IETF RFC 2863",
    sourceUrl: "https://www.rfc-editor.org/rfc/rfc2863.html",
    parent: "ifXEntry",
    table: "ifXTable",
    row: "ifXEntry",
    index: "ifIndex",
    notificationObjects: [],
    related: ["ifDescr", "ifAlias", "ifOperStatus"],
    intent: ["interface name", "port name"],
    description: "Textual name of an interface assigned by the local device.",
    enumValues: [],
    command: "snmpwalk -v2c -c <community> <host> 1.3.6.1.2.1.31.1.1.1.1"
  },
  {
    ...standardsTrust,
    module: "SNMPv2-MIB",
    symbol: "sysUpTime",
    oid: "1.3.6.1.2.1.1.3",
    kind: "scalar",
    access: "read-only",
    status: "current",
    syntax: "TimeTicks",
    syntaxDetail: {
      base: "TimeTicks",
      textualConvention: null,
      displayHint: null,
      units: "hundredths of a second",
      constraints: [],
      enums: {},
      bits: {}
    },
    revision: "2002-10-16",
    source: "IETF RFC 3418",
    sourceUrl: "https://www.rfc-editor.org/rfc/rfc3418.html",
    parent: "system",
    table: null,
    row: null,
    index: ".0 instance",
    notificationObjects: [],
    related: ["sysName", "sysDescr", "coldStart"],
    intent: ["uptime", "device uptime", "restart time"],
    description: "Time since the network management portion was last initialized.",
    enumValues: [],
    command: "snmpget -v2c -c <community> <host> 1.3.6.1.2.1.1.3.0"
  },
  {
    ...standardsTrust,
    module: "HOST-RESOURCES-MIB",
    symbol: "hrProcessorLoad",
    oid: "1.3.6.1.2.1.25.3.3.1.2",
    kind: "column",
    access: "read-only",
    status: "current",
    syntax: "Integer32 (0..100)",
    syntaxDetail: {
      base: "Integer32",
      textualConvention: null,
      displayHint: null,
      units: "percent",
      constraints: ["0..100"],
      enums: {},
      bits: {}
    },
    revision: "2000-03-06",
    source: "IETF RFC 2790",
    sourceUrl: "https://www.rfc-editor.org/rfc/rfc2790.html",
    parent: "hrProcessorEntry",
    table: "hrProcessorTable",
    row: "hrProcessorEntry",
    index: "hrDeviceIndex",
    notificationObjects: [],
    related: ["hrDeviceDescr", "hrSystemUptime"],
    intent: ["processor load", "cpu usage", "cpu load"],
    description: "One-minute average percentage of processor busy time.",
    enumValues: [],
    command: "snmpwalk -v2c -c <community> <host> 1.3.6.1.2.1.25.3.3.1.2"
  },
  {
    ...standardsTrust,
    module: "IF-MIB",
    symbol: "linkDown",
    oid: "1.3.6.1.6.3.1.1.5.3",
    kind: "notification",
    access: "not-accessible",
    status: "current",
    syntax: "NOTIFICATION-TYPE",
    syntaxDetail: {
      base: "NOTIFICATION-TYPE",
      textualConvention: null,
      displayHint: null,
      units: null,
      constraints: [],
      enums: {},
      bits: {}
    },
    revision: "2000-06-14",
    source: "IETF RFC 2863",
    sourceUrl: "https://www.rfc-editor.org/rfc/rfc2863.html",
    parent: "snmpTraps",
    table: null,
    row: null,
    index: null,
    notificationObjects: ["ifIndex", "ifAdminStatus", "ifOperStatus"],
    related: ["ifIndex", "ifAdminStatus", "ifOperStatus"],
    intent: ["link down trap", "interface down notification"],
    description: "Signals that an interface entered the down state.",
    enumValues: [],
    command: "# Notification OID; inspect its varbind objects instead of polling this OID."
  }
];
